# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./docker/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - pgsql
            - socket.test
            - vue_app.test
            - react_app.test
    socket.test:
        image: node
        ports:
            - '${SOCKET_APP_PORT:-3000}:3000'
        command: [ "npm","run","start" ]
        environment:
            SOCKET_APP_HOST: '0.0.0.0'
            SOCKET_APP_PORT: '3000'
        working_dir: '/var/www/html/socket'
        volumes:
            - './socket:/var/www/html/socket'
        networks:
            - sail
    vue_app.test:
        image: node
        ports:
            - '${VUE_APP_PORT:-4000}:4000'
        environment:
            HOST: '0.0.0.0'
            PORT: '${VUE_APP_PORT:-4000}'
        command: [ "npm","run","serve" , "--", "--port", '4000' ]
        working_dir: '/var/www/html/vue_app'
        volumes:
            - './vue_app:/var/www/html/vue_app'
        networks:
            - sail
    react_app.test:
        image: node
        ports:
            - '${REACT_APP_PORT:-5000}:5000'
        environment:
            HOST: '0.0.0.0'
            PORT: '${REACT_APP_PORT:-5000}'
        command: [ "npm","run","start" , "--", "--port", '5000' ]
        working_dir: '/var/www/html/react_app'
        volumes:
            - './react_app:/var/www/html/react_app'
        networks:
            - sail
    pgsql:
        image: 'postgres:13'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'sailpgsql:/var/lib/postgresql/data'
        networks:
            - sail
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sailpgsql:
        driver: local
